import React from 'react';
import FloatingLabel from "../../atoms/FloatingLabel";
import {Col, Form, Row} from "react-bootstrap";

const FormCard = ({formik}) => {
  return (
    <Form>
      <FloatingLabel
        label="Имя"
        className="mb-3"
      >
        <input
          name="name"
          value={formik.values.name}
          onChange={formik.handleChange}
          placeholder=" "
        />
      </FloatingLabel>
      <hr/>
      <Row>
        <Col>
          <FloatingLabel
            label="Сила"
            className="mb-3"
          >
            <input
              type="number"
              name="strength"
              value={formik.values.strength}
              onChange={formik.handleChange}
              placeholder="Сила"
            />
          </FloatingLabel>
          <FloatingLabel
            label="Ловкость"
            className="mb-3"
          >
            <input
              type="number"
              name="dexterity"
              value={formik.values.dexterity}
              onChange={formik.handleChange}
              placeholder="Ловкость"
            />
          </FloatingLabel>
          <FloatingLabel
            label="Выносливость"
            className="mb-3"
          >
            <input
              type="number"
              name="constitution"
              value={formik.values.constitution}
              onChange={formik.handleChange}
              placeholder="Выносливость"
            />
          </FloatingLabel>
        </Col>
        <Col>
          <FloatingLabel
            label="Интелект"
            className="mb-3"
          >
            <input
              type="number"
              name="intelligence"
              value={formik.values.intelligence}
              onChange={formik.handleChange}
              placeholder="Интелект"
            />
          </FloatingLabel>
          <FloatingLabel
            label="Мудрость"
            className="mb-3"
          >
            <input
              type="number"
              name="wisdom"
              value={formik.values.wisdom}
              onChange={formik.handleChange}
              placeholder="Мудрость"
            />
          </FloatingLabel>
          <FloatingLabel
            label="Харизма"
          >
            <input
              type="number"
              name="charisma"
              value={formik.values.charisma}
              onChange={formik.handleChange}
              placeholder="Харизма"
            />
          </FloatingLabel>
        </Col>
      </Row>
      <hr />
      <Row>
        <Col>
          <FloatingLabel
            label="Скорость"
            className="mb-3"
          >
            <input
              type="number"
              name="speed"
              value={formik.values.speed}
              onChange={formik.handleChange}
              placeholder="Скорость"
            />
          </FloatingLabel>
          <FloatingLabel
            label="Класс Брони"
            className="mb-3"
          >
            <input
              type="number"
              name="armor"
              value={formik.values.armor}
              onChange={formik.handleChange}
              placeholder="Класс Брони"
            />
          </FloatingLabel>
        </Col>
        <Col>
          <FloatingLabel
            label="Пас. внимание"
            className="mb-3"
          >
            <input
              type="number"
              name="attention"
              value={formik.values.attention}
              onChange={formik.handleChange}
              placeholder="Пас. внимание"
            />
          </FloatingLabel>
          <FloatingLabel
            label="Инициатива"
            className="mb-3"
          >
            <input
              type="number"
              name="initiativeBonus"
              value={formik.values.initiativeBonus}
              onChange={formik.handleChange}
              placeholder="Инициатива"
            />
          </FloatingLabel>
        </Col>
      </Row>
    </Form>
  );
};

export default FormCard;